### ISSUE TITLE
Hydra not working in Colab.

### ISSUE THREAD

**Issue by ashercn97** [explodinggradients/Funtuner#18]
I am trying to use this in Google Colab. I have a GPU runtime set up. When I run it (wihtout changing any configs and just doing the exact command you said in the README) it says hydra isnt installed. So, I try to install it and it wont let me. Is there a requirements file that I can install? Right now, I am just cloning the repo, and then doing %cd Funtuner . I would love to use this so if you know what is going wrong id love to hear!

**Comment by ashercn97** [comment]
I am new to this whole thing so sorry if this is a stupid question.

**Comment by shahules786** [comment]
@ashercn97 This is WIP. I'll add the requirements and clean up the README today. 
Although I wouldn't recommend using Funtuner with colab right now as I haven't tested it in colab.

**Comment by ashercn97** [comment]
@shahules786 Where would you suggest using it? Im really new to this so ty for your help! Would the Microsoft Azure machine learning notebooks work?

**Comment by ashercn97** [comment]
@shahules786 Do you think it will work in Amazon SageMaker Studio Lab? If so, how do i go about using it?

**Comment by shahules786** [comment]
Hi,  you can use it anywhere where you have access terminal to install and run python applications.

**Comment by ashercn97** [comment]
@shahules786 Okay. Thanks!
